### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by IM-IgniteDEV** [DemonWav/MinecraftDevIntelliJ#1736]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version 2021.3-1.5.15
* IntelliJ version Build IntelliJ IDEA 2021.3 (#IU-213.5744.223)
* Operating System (this has come up enough times to be worth noting): Windows 10
* (optional) Target platform, if relevant
  * E.g., Bukkit, Forge, Mixin, etc: Paper

com.demonwav.mcdev.creator.exception.ProjectCreatorException: Build steps completed:
    com.demonwav.mcdev.platform.bukkit.creator.BukkitProjectConfig
        com.demonwav.mcdev.platform.bukkit.creator.BukkitDependenciesStep
        com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep
            com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$Companion$setupDirs$1
          > com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$Companion$setupCore$1

	at com.demonwav.mcdev.creator.MinecraftProjectCreator$CreateTask.run(MinecraftProjectCreator.kt:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/application/options/IndentOptionsEditorBase
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:450)
	at com.demonwav.mcdev.util.UtilsKt.invokeAndWait(utils.kt:75)
	at com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep.runStep(maven-steps.kt:249)
	at com.demonwav.mcdev.creator.MinecraftProjectCreator$CreateTask.run(MinecraftProjectCreator.kt:185)
	at com.demonwav.mcdev.creator.MinecraftProjectCreator$CreateTask.run(MinecraftProjectCreator.kt:101)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/application/options/IndentOptionsEditorBase
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.registerSettingsPageProvider(LanguageCodeStyleSettingsProvider.java:405)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.calcSettingPagesProviders(LanguageCodeStyleSettingsProvider.java:386)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.lambda$getSettingsPagesProviders$2(LanguageCodeStyleSettingsProvider.java:379)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.getSettingsPagesProviders(LanguageCodeStyleSettingsProvider.java:379)
	at com.intellij.psi.codeStyle.CodeStyleSettingsServiceImpl.getCustomCodeStyleSettingsFactories(CodeStyleSettingsServiceImpl.java:64)
	at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.initCustomSettings(CustomCodeStyleSettingsManager.java:25)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:101)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.createSettings(CodeStyleSettingsManager.java:52)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.setMainProjectCodeStyle(ProjectCodeStyleSettingsManager.java:79)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.<init>(ProjectCodeStyleSettingsManager.java:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:102)
	at com.intellij.application.options.CodeStyle.getSettings(CodeStyle.java:57)
	at com.intellij.application.options.CodeStyle.getFacade(CodeStyle.java:508)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.createDocument(FileDocumentManagerImpl.java:218)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:51)
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:284)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:579)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:673)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:53)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:447)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternalSuper(XmlTagImpl.java:336)
	at com.intellij.psi.impl.source.xml.XmlTagImpl$XmlTagImplDelegate.addInternalSuper(XmlTagImpl.java:378)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.bodyInsert(XmlTagDelegate.java:1046)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.addInternal(XmlTagDelegate.java:981)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternal(XmlTagImpl.java:311)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.addInnerBefore(CompositePsiElement.java:304)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.add(CompositePsiElement.java:134)
	at com.intellij.psi.impl.source.xml.XmlTagValueImpl.setText(XmlTagValueImpl.java:122)
	at com.intellij.psi.impl.source.xml.XmlTagValueImpl.setText(XmlTagValueImpl.java:108)
	at com.intellij.util.xml.impl.DomInvocationHandler.setTagValue(DomInvocationHandler.java:695)
	at com.intellij.util.xml.impl.DomInvocationHandler.lambda$setValue$0(DomInvocationHandler.java:134)
	at com.intellij.util.xml.impl.DomManagerImpl.runChange(DomManagerImpl.java:297)
	at com.intellij.util.xml.impl.DomInvocationHandler.setValue(DomInvocationHandler.java:134)
	at com.intellij.util.xml.impl.SetInvocation.invoke(SetInvocation.java:47)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:658)
	at com.intellij.util.xml.GenericDomValue$$EnhancerByJetBrainsMainCglib$$2e754a1e.setValue(<generated>)
	at com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$Companion$setupCore$1.invoke(maven-steps.kt:116)
	at com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$Companion$setupCore$1.invoke(maven-steps.kt:104)
	at com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$runStep$$inlined$runWriteTask$1$1$lambda$1.compute(utils.kt:316)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$compute$3(WriteCommandAction.java:167)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.compute(WriteCommandAction.java:167)
	at com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$runStep$$inlined$runWriteTask$1$1.compute(utils.kt:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:956)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:935)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:956)
	at com.demonwav.mcdev.creator.buildsystem.maven.BasicMavenStep$runStep$$inlined$runWriteTask$1.invoke(utils.kt:37)
	at com.demonwav.mcdev.util.UtilsKt$invokeAndWait$1.run(utils.kt:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:450)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.application.options.IndentOptionsEditorBase PluginClassLoader(plugin=PluginDescriptor(name=Minecraft Development, id=com.demonwav.minecraft-dev, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.5744.223.plugins\Minecraft Development, version=2021.3-1.5.15, package=null, isBundled=false), packagePrefix=null, instanceId=319, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 113 more

**Comment by RedNesto** [comment]
Fixed in 1.5.16
