### ISSUE TITLE
Exception In Plugin Minecraft Development

### ISSUE THREAD

**Issue by manmaed** [DemonWav/MinecraftDevIntelliJ#1849]
IntelliJ: IntelliJ IDEA 2021.2.4 (Community Edition) Build #IC-212.5712.43
OS: Windows 10 Pro
Minecraft Dev: 2021.2-1.5.19-328

Trying to load 1.19 dev env
```
java.lang.IllegalArgumentException: Multiple entries with same key: MemberReference(name=	0, descriptor=f_202497_, owner=net.minecraft.nbt.visitors.FieldSelector, matchAllNames=false, matchAllDescs=false)=MemberReference(name=f_202497_, descriptor=f_202497_, owner=net.minecraft.nbt.visitors.FieldSelector, matchAllNames=false, matchAllDescs=false) and MemberReference(name=	0, descriptor=f_202497_, owner=net.minecraft.nbt.visitors.FieldSelector, matchAllNames=false, matchAllDescs=false)=MemberReference(name=f_202497_, descriptor=f_202497_, owner=net.minecraft.nbt.visitors.FieldSelector, matchAllNames=false, matchAllDescs=false)
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:211)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:205)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableBiMap.fromEntryArray(RegularImmutableBiMap.java:86)
	at com.google.common.collect.ImmutableBiMap$Builder.build(ImmutableBiMap.java:291)
	at com.demonwav.mcdev.platform.mcp.srg.TinySrgParser.parseSrg(TinySrgParser.kt:68)
	at com.demonwav.mcdev.platform.mcp.srg.SrgManager$parse$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
	```

**Comment by RedNesto** [comment]
Looks like `createMcpToSrg` now outputs TSRG2 which is apparently not supported by the custom parser we use. You can work around this by adding the following to your `build.gradle`
```gradle
tasks.named('createMcpToSrg').configure {
    format = 'TSRG'
}
```

**Comment by RedNesto** [comment]
The new parser will be used by default. If any issue arises because of it one can use the old parser by unchecking `mcdev.new.tsrg.parser` in the registry.
