### ISSUE TITLE
Error while creating a new Forge project

### ISSUE THREAD

**Issue by MikaYxCoding** [DemonWav/MinecraftDevIntelliJ#1874]
## Intellij Idea
IntelliJ IDEA 2018.3.6 (Community Edition)
Build #IC-183.6156.11, built on March 25, 2019
JRE: 1.8.0_241-b07 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation
Windows 10 10.0

## Plugin
Minecraft Development v2018.3-1.2.20

## Info
This happens every time I try to create a new Forge project.

First I get an error while trying to retrieve Forge, MCP and Minecraft versions.
![image](https://user-images.githubusercontent.com/100044115/182688879-1089092a-7171-46c5-b851-c2553aeb4d9a.png)

After I decided to continue anyway and this IDE error appears.
```
kotlin.UninitializedPropertyAccessException: lateinit property pluginName has not been initialized
	at com.demonwav.mcdev.platform.ProjectConfiguration.getPluginName(ProjectConfiguration.kt:26)
	at com.demonwav.mcdev.creator.MinecraftProjectCreator.create(MinecraftProjectCreator.kt:54)
	at com.demonwav.mcdev.creator.MinecraftModuleBuilder$setupRootModel$r$1.invoke(MinecraftModuleBuilder.kt:58)
	at com.demonwav.mcdev.creator.MinecraftModuleBuilder$setupRootModel$r$1.invoke(MinecraftModuleBuilder.kt:35)
	at com.demonwav.mcdev.creator.MinecraftModuleBuilder$sam$com_intellij_openapi_project_DumbAwareRunnable$0.run(MinecraftModuleBuilder.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:356)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:348)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:185)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$7(ProjectManagerImpl.java:413)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by SizableShrimp** [comment]
IntelliJ 2018.x has not been supported for a while. Upgrade

**Comment by MikaYxCoding** [comment]
I've had problems with higher versions of Intellij due to my computer. 2018.3.6 is the version that has worked for me. Idk, maybe I'll try upgrading.
