### ISSUE TITLE
Template not found: Bukkit pom.xml

### ISSUE THREAD

**Issue by bierdosenhalter** [DemonWav/MinecraftDevIntelliJ#1883]
McDev 2022.1-1.5.20
IntelliJ IDEA 2022.1.4
Windows 10
Java 1.8
Bukkit

```
com.demonwav.mcdev.creator.exception.ProjectCreatorException: Build steps completed:
    com.demonwav.mcdev.platform.bukkit.creator.BukkitProjectConfig

	at com.demonwav.mcdev.creator.MinecraftProjectCreator$CreateTask.run(MinecraftProjectCreator.kt:121)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Template not found: Bukkit pom.xml
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getTemplateFromManager(FileTemplateManagerImpl.java:294)
	at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.getJ2eeTemplate(FileTemplateManagerImpl.java:280)
	at com.demonwav.mcdev.platform.BaseTemplate.applyTemplate(BaseTemplate.kt:23)
	at com.demonwav.mcdev.platform.bukkit.creator.BukkitTemplate.applyPom(BukkitTemplate.kt:47)
	at com.demonwav.mcdev.platform.bukkit.creator.BukkitMavenCreator.getSteps(BukkitProjectCreator.kt:69)
	at com.demonwav.mcdev.creator.MinecraftProjectCreator$CreateTask.run(MinecraftProjectCreator.kt:100)
	... 20 more
```

**Comment by DenWav** [comment]
I don't understand how this is possible. Not sure what we can do about it.
