### ISSUE TITLE
unable to open any projects

### ISSUE THREAD

**Issue by amirparsadd** [DemonWav/MinecraftDevIntelliJ#2071]
### Minecraft Development for IntelliJ plugin version

latest

### IntelliJ version

comunity 2022 2.4

### Operating System

win10

### Description of the bug

full stack trace : 
```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'n2' of com/intellij/openapi/vfs/newvfs/persistent/PersistentFSImpl.namesEqual must not be null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'n2' of com/intellij/openapi/vfs/newvfs/persistent/PersistentFSImpl.namesEqual must not be null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:829)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$2.run(ComponentManagerImpl.kt:1050)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'n2' of com/intellij/openapi/vfs/newvfs/persistent/PersistentFSImpl.namesEqual must not be null
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.$$$reportNull$$$0(PersistentFSImpl.java)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.namesEqual(PersistentFSImpl.java)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findExistingChildInfo(PersistentFSImpl.java:474)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$findChildInfo$4(PersistentFSImpl.java:416)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:349)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:453)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:150)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:538)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:63)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:123)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.findByUrl(VirtualFileManagerImpl.java:372)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.findFileByUrl(VirtualFileManagerImpl.java:359)
	at com.intellij.workspaceModel.ide.impl.VirtualFileUrlBridge.findVirtualFile(VirtualFileUrlBridge.kt:41)
	at com.intellij.workspaceModel.ide.impl.VirtualFileUrlBridge.getFile(VirtualFileUrlBridge.kt:18)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.SourceFolderBridge.getFile(ContentFolderBridge.kt:37)
	at com.demonwav.mcdev.facet.MinecraftFacet$updateRoots$2.invoke(MinecraftFacet.kt:127)
	at com.demonwav.mcdev.facet.MinecraftFacet$updateRoots$2.invoke(MinecraftFacet.kt:127)
	at com.demonwav.mcdev.util.SequencesKt$filterNotNull$1.invoke(sequences.kt:31)
	at com.demonwav.mcdev.util.SequencesKt$filterNotNull$1.invoke(sequences.kt:31)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.demonwav.mcdev.facet.MinecraftFacet.updateRoots(MinecraftFacet.kt:299)
	at com.demonwav.mcdev.facet.MinecraftFacet.refresh(MinecraftFacet.kt:105)
	at com.demonwav.mcdev.facet.MinecraftFacet.initFacet(MinecraftFacet.kt:66)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleBridgeImpl.initFacets(ModuleBridgeImpl.kt:100)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleManagerBridgeImpl.loadModules(ModuleManagerBridgeImpl.kt:119)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleBridgeLoaderService.loadModules(ModuleBridgeLoaderService.kt:58)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleBridgeLoaderService.<init>(ModuleBridgeLoaderService.kt:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt:1068)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invoke(ComponentManagerImpl.kt:1033)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.run(ComponentManagerImpl.kt:55)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	... 5 more
```

**Comment by RedNesto** [comment]
This looks like a platform bug, nothing we can do about it.
