### ISSUE TITLE
I can't get the version of Bukkit

### ISSUE THREAD

**Issue by lengzu** [DemonWav/MinecraftDevIntelliJ#2076]
### Minecraft Development for IntelliJ plugin version

1.6.6

### IntelliJ version

2022.3

### Operating System

win10

### Target platform

Bukkit, Spigot, Paper, Velocity

### Description of the bug

Connection reset
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:85)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:22)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:40)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.github.kittinunf.fuel.core.DeserializableKt.await(Deserializable.kt:233)
	com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invokeSuspend(Coroutines.kt:33)
	com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invoke(Coroutines.kt)
	kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	com.demonwav.mcdev.creator.PlatformVersionKt.doCall(PlatformVersion.kt:110)
	com.demonwav.mcdev.creator.PlatformVersionKt.getText(PlatformVersion.kt:67)
	com.demonwav.mcdev.creator.PlatformVersionKt.getVersionJson(PlatformVersion.kt:53)
	com.demonwav.mcdev.creator.PlatformVersionKt.getVersionSelector(PlatformVersion.kt:107)
	com.demonwav.mcdev.platform.bukkit.creator.AbstractBukkitPlatformStep$computeData$2$1.invokeSuspend(ui-steps.kt:82)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: Connection reset
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:70)
Caused by: java.net.SocketException: Connection reset
	java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:145)
	com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:79)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:67)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:21)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:40)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.github.kittinunf.fuel.core.DeserializableKt.await(Deserializable.kt:233)
	com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invokeSuspend(Coroutines.kt:33)
	com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invoke(Coroutines.kt)
	kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	com.demonwav.mcdev.creator.PlatformVersionKt.doCall(PlatformVersion.kt:110)
	com.demonwav.mcdev.creator.PlatformVersionKt.getText(PlatformVersion.kt:67)
	com.demonwav.mcdev.creator.PlatformVersionKt.getVersionJson(PlatformVersion.kt:53)
	com.demonwav.mcdev.creator.PlatformVersionKt.getVersionSelector(PlatformVersion.kt:107)
	com.demonwav.mcdev.platform.bukkit.creator.AbstractBukkitPlatformStep$computeData$2$1.invokeSuspend(ui-steps.kt:82)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:85)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:22)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:40)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	at com.github.kittinunf.fuel.core.DeserializableKt.await(Deserializable.kt:233)
	at com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invokeSuspend(Coroutines.kt:33)
	at com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invoke(Coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.demonwav.mcdev.creator.PlatformVersionKt.doCall(PlatformVersion.kt:110)
	at com.demonwav.mcdev.creator.PlatformVersionKt.getText(PlatformVersion.kt:67)
	at com.demonwav.mcdev.creator.PlatformVersionKt.getVersionJson(PlatformVersion.kt:53)
	at com.demonwav.mcdev.creator.PlatformVersionKt.getVersionSelector(PlatformVersion.kt:107)
	at com.demonwav.mcdev.platform.bukkit.creator.AbstractBukkitPlatformStep$computeData$2$1.invokeSuspend(ui-steps.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: Connection reset
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:70)
Caused by: java.net.SocketException: Connection reset
	java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:145)
	com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:79)
	com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:67)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:21)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:40)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.github.kittinunf.fuel.core.DeserializableKt.await(Deserializable.kt:233)
	com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invokeSuspend(Coroutines.kt:33)
	com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invoke(Coroutines.kt)
	kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	com.demonwav.mcdev.creator.PlatformVersionKt.doCall(PlatformVersion.kt:110)
	com.demonwav.mcdev.creator.PlatformVersionKt.getText(PlatformVersion.kt:67)
	com.demonwav.mcdev.creator.PlatformVersionKt.getVersionJson(PlatformVersion.kt:53)
	com.demonwav.mcdev.creator.PlatformVersionKt.getVersionSelector(PlatformVersion.kt:107)
	com.demonwav.mcdev.platform.bukkit.creator.AbstractBukkitPlatformStep$computeData$2$1.invokeSuspend(ui-steps.kt:82)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
	at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:70)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:145)
	at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:79)
	at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:67)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:21)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:40)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	at com.github.kittinunf.fuel.core.DeserializableKt.await(Deserializable.kt:233)
	at com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invokeSuspend(Coroutines.kt:33)
	at com.demonwav.mcdev.creator.PlatformVersionKt$doCall$$inlined$awaitString$default$1.invoke(Coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.demonwav.mcdev.creator.PlatformVersionKt.doCall(PlatformVersion.kt:110)
	at com.demonwav.mcdev.creator.PlatformVersionKt.getText(PlatformVersion.kt:67)
	at com.demonwav.mcdev.creator.PlatformVersionKt.getVersionJson(PlatformVersion.kt:53)
	at com.demonwav.mcdev.creator.PlatformVersionKt.getVersionSelector(PlatformVersion.kt:107)
	at com.demonwav.mcdev.platform.bukkit.creator.AbstractBukkitPlatformStep$computeData$2$1.invokeSuspend(ui-steps.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by RedNesto** [comment]
This is an issue with your internet or something that prevents you from reaching the 2 different endpoints. Nothing we can fix on our end
