### ISSUE TITLE
Creating new project failed

### ISSUE THREAD

**Issue by SinanAkkoyun** [DemonWav/MinecraftDevIntelliJ#2094]
### Minecraft Development for IntelliJ plugin version

latest

### IntelliJ version

latest

### Operating System

Windows 11

### Target platform

Fabric

### Description of the bug

When creating a new fabric project (1.20.1, latest fabric and fabric API), it throws this error when trying to run the client:

```diff
- [16:02:17] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
-[16:02:17] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
-java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
-    at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:214)
-    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
-    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
-    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-    at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

`gradle.properties`
```sh
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
    # check these on https://modmuss50.me/fabric.html
    minecraft_version=1.20.1
    yarn_mappings=1.20.1+build.10
    loader_version=0.14.21

# Mod Properties
    mod_version = 1.0-SNAPSHOT
    maven_group = sinan
    archives_base_name = luminance

# Dependencies
    # check this on https://modmuss50.me/fabric.html
    fabric_version=0.86.1+1.20.1
```

**Comment by Randommist** [comment]
And how was this decided?
