### ISSUE TITLE
Syntax highlighting stops in one Java file

### ISSUE THREAD

**Issue by AlexiyOrlov** [DemonWav/MinecraftDevIntelliJ#2126]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

232.9921.47

### Operating System

Windows 10

### Target platform

Minecraft Forge

### Description of the bug

I was working on a new project, and syntax highlighting stopped working in one file. I reported this to Jetbrains, and they found it was this plugin's issue. 

```java 2023-09-17 19:06:01,027 [  10325] SEVERE - #c.i.c.d.i.GeneralHighlightingPass - In file: file://C:/Users/alexi/Minecraft/k-golems/src/main/resources/assets/k_golems/lang/en_us.json
java.lang.IllegalArgumentException: Must pass FS root path, but got: 'D:///', which has a parent 'D:'. Use NewVirtualFileSystem.extractRootPath() for obtaining root path
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:1495)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.cacheRootsByUrls(PersistentFSImpl.java:1620)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.cacheSingleMissedRootFromPersistence(PersistentFSImpl.java:1602)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.ascendUntilCachedParent(PersistentFSImpl.java:1685)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.find(PersistentFSImpl.java:1806)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1567)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:64)
	at com.intellij.util.indexing.FileBasedIndexImpl.findFileById(FileBasedIndexImpl.java:1184)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValuesInScope$9(FileBasedIndexEx.java:401)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$10(FileBasedIndexEx.java:434)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$6(FileBasedIndexEx.java:324)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:324)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:436)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:394)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1145)
	at com.intellij.util.indexing.FileBasedIndexEx.getValues(FileBasedIndexEx.java:139)
	at com.demonwav.mcdev.translations.index.TranslationIndex$Companion.getEntries(TranslationIndex.kt:90)
	at com.demonwav.mcdev.translations.index.TranslationIndex$Companion.getAllDefaultEntries(TranslationIndex.kt:84)
	at com.demonwav.mcdev.translations.intentions.TranslationFileAnnotator.checkEntryMatchesDefault(TranslationFileAnnotator.kt:68)
	at com.demonwav.mcdev.translations.intentions.TranslationFileAnnotator.annotate(TranslationFileAnnotator.kt:39)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:291)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:234)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2023-09-17 19:06:01,031 [  10329] SEVERE - #c.i.c.d.i.GeneralHighlightingPass - IntelliJ IDEA 2023.2.2  Build #IC-232.9921.47
2023-09-17 19:06:01,031 [  10329] SEVERE - #c.i.c.d.i.GeneralHighlightingPass - JDK: 17.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-09-17 19:06:01,032 [  10330] SEVERE - #c.i.c.d.i.GeneralHighlightingPass - OS: Windows 10
2023-09-17 19:06:01,032 [  10330] SEVERE - #c.i.c.d.i.GeneralHighlightingPass - Plugin to blame: Minecraft Development version: 2023.2-1.6.10
```

K-Golems is a different project, current one is named 'tnt-gun'

**Comment by RedNesto** [comment]
Looks like https://youtrack.jetbrains.com/issue/IDEA-327881/IllegalArgumentException-Must-pass-FS-root-path-but-got-D-which-has-a-parent-D
which is a platform bug that'll be fixed in 2023.3, I don't know if they'll backport it to 2023.2.
