### ISSUE TITLE
Unable to fetch Fabric versions

### ISSUE THREAD

**Issue by Wani4ka** [DemonWav/MinecraftDevIntelliJ#2129]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

2023.2.1 (Ultimate Edition)

### Operating System

Windows 11 Home 22H2

### Target platform

Fabric

### Description of the bug

When I'm trying to create a fabric project, I can't fetch versions:

![image](https://github.com/minecraft-dev/MinecraftDev/assets/31739611/980c7695-1b62-444e-be76-be929f244d5d)

Using VPN (WARP+) doesn't help.

Here's the stack trace of the error:
```
HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:46)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.demonwav.mcdev.platform.fabric.util.FabricApiVersions$Companion.downloadData(FabricApiVersions.kt:48)
	com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricApiVersions$1.invokeSuspend(ui-steps.kt:68)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.prepareResponse(SuspendableRequest.kt:32)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:43)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.demonwav.mcdev.platform.fabric.util.FabricApiVersions$Companion.downloadData(FabricApiVersions.kt:48)
	com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricApiVersions$1.invokeSuspend(ui-steps.kt:68)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:46)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	at com.demonwav.mcdev.platform.fabric.util.FabricApiVersions$Companion.downloadData(FabricApiVersions.kt:48)
	at com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricApiVersions$1.invokeSuspend(ui-steps.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:46)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.demonwav.mcdev.platform.fabric.util.FabricVersions$Companion.downloadData(FabricVersions.kt:54)
	com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricVersions$1.invokeSuspend(ui-steps.kt:67)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.prepareResponse(SuspendableRequest.kt:32)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:43)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.demonwav.mcdev.platform.fabric.util.FabricVersions$Companion.downloadData(FabricVersions.kt:54)
	com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricVersions$1.invokeSuspend(ui-steps.kt:67)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


		at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
		at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:46)
		at com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
		at com.demonwav.mcdev.platform.fabric.util.FabricVersions$Companion.downloadData(FabricVersions.kt:54)
		at com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricVersions$1.invokeSuspend(ui-steps.kt:67)
		... 8 more
	Caused by: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.prepareResponse(SuspendableRequest.kt:32)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:43)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.demonwav.mcdev.platform.fabric.util.FabricVersions$Companion.downloadData(FabricVersions.kt:54)
	com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricVersions$1.invokeSuspend(ui-steps.kt:67)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

		at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
	Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 403 Forbidden
		at com.github.kittinunf.fuel.core.requests.SuspendableRequest.prepareResponse(SuspendableRequest.kt:32)
		at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:43)
		at com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
		at com.demonwav.mcdev.platform.fabric.util.FabricVersions$Companion.downloadData(FabricVersions.kt:54)
		at com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricVersions$1.invokeSuspend(ui-steps.kt:67)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 403 Forbidden
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.prepareResponse(SuspendableRequest.kt:32)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:43)
	com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	com.demonwav.mcdev.platform.fabric.util.FabricApiVersions$Companion.downloadData(FabricApiVersions.kt:48)
	com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricApiVersions$1.invokeSuspend(ui-steps.kt:68)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 403 Forbidden
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.prepareResponse(SuspendableRequest.kt:32)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:43)
	at com.github.kittinunf.fuel.core.requests.SuspendableRequest.await(SuspendableRequest.kt:64)
	at com.demonwav.mcdev.platform.fabric.util.FabricApiVersions$Companion.downloadData(FabricApiVersions.kt:48)
	at com.demonwav.mcdev.platform.fabric.creator.FabricPlatformStep$computeData$2$fabricApiVersions$1.invokeSuspend(ui-steps.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by RedNesto** [comment]
This is an occasional issue with the fabric repo, nothing we can do about it.
