### ISSUE TITLE
Opening a paper project throws an exception

### ISSUE THREAD

**Issue by lucyydotp** [DemonWav/MinecraftDevIntelliJ#2181]
### Minecraft Development for IntelliJ plugin version

2023.3-1.6.11

### IntelliJ version

IU-233.11799.300

### Operating System

macOS 14.1.1

### Target platform

Paper

### Description of the bug

```
Unhandled exception in [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelling}@461bde85, Dispatchers.Default]

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[DefaultDispatcher-worker-13,5,main] 939687859 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1335125230
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:143)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:65)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecute(ActionManagerImpl.kt:1216)
	at com.demonwav.mcdev.facet.ProjectReimporter.reimport(ProjectReimporter.kt:52)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.doCheck(MinecraftFacetDetector.kt:118)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener$doCheck$1.invokeSuspend(MinecraftFacetDetector.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelled}@461bde85, Dispatchers.Default]
```

I'm not sure exactly when this happens, it's quite inconsistent. Sometimes entire facets fail to load, so the files aren't in the file view at all. It only seems to affect Paper projects - I have a few Fabric mods cloned but they load fine.

**Comment by RedNesto** [comment]
Fix in nightly
