### ISSUE TITLE
more than one module named `cpw.mods.securejarhandler`

### ISSUE THREAD

**Issue by SaltSouls** [DemonWav/MinecraftDevIntelliJ#2262]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.3

### IntelliJ version

2023.3.4

### Operating System

Arch Linux

### Target platform

Minecraft Forge

### Description of the bug

After setting up the template project and running the `genIntellijRuns` task, when trying to runClient I get this error:
```
Exception in thread "main" java.lang.module.ResolutionException: Module org.antlr.antlr4.runtime reads more than one module named cpw.mods.securejarhandler
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
```
I have tried rerunning the gen task, remaking the project, switching the forge version, and removing the `.gradle` file where all the libraries are stored, but nothing has fixed this issue. This would seem to be a recent issue as older mods I started using this plugin don't run into the same issue. I should also note that the module that reads more than one of the `cpw.mods.securejarhandler` modules seems to change pretty regularly. No idea what is causing this or how I'm even supposed to go about fixing/debugging it.

**Comment by Sxtkl123** [comment]
Try it with `forge_version=47.2.0` in your build.gradle or just try to create a new project with forge version 47.2.0 may work. I met the same issue with you and solve it like what I said.
