### ISSUE TITLE
Unable to Create Project

### ISSUE THREAD

**Issue by Conutik** [DemonWav/MinecraftDevIntelliJ#2267]
### Minecraft Development for IntelliJ plugin version

2022.1-1.6.2

### IntelliJ version

IntelliJ IDEA 2022.1.4 (Ultimate Edition) Build #IU-221.6008.13, built on July 19, 2022 Licensed to Zaid Khawaj Subscription is active until May 4, 2024. For educational use only. Runtime version: 11.0.15+10-b2043.56 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 11 10.0 GC: G1 Young Generation, G1 Old Generation Memory: 2026M Cores: 12 Non-Bundled Plugins:     com.tabnine.TabNine (1.63.0)     com.markskelton.one-dark-theme (5.10.0)     org.jetbrains.kotlin (221-1.8.10-release-430-IJ5591.52)     jd-intellij (0.8.1)     com.github.copilot (1.4.6.4092)     com.mallowigi (64.0.0)     com.almightyalpaca.intellij.plugins.discord (1.10.0)     com.hotswap.agent.plugin (1.3.0)     com.github.masahirosuzuka.PhoneGapIntelliJPlugin (221.6008.18)     com.demonwav.minecraft-dev (2022.1-1.6.2)  Kotlin: 221-1.8.10-release-430-IJ5591.52

### Operating System

Windows 11

### Description of the bug

Whenever I try to create a New Project I don't get anything opened however, when I disabled `Minecraft Development` plugin it opens and lets me create a new project. 

When I re-enable the plugin and try to create a new project the box opens however I can't click on the `Minecraft` Button.

The error I get:

java.lang.NoSuchMethodError: 'com.intellij.openapi.ui.validation.DialogValidation$WithParameter com.intellij.openapi.ui.validation.ValidationsKt.getCHECK_GROUP_ID_FORMAT()'
	at com.demonwav.mcdev.creator.buildsystem.BuildSystemPropertiesStep$setupUI$1$1.invoke(BuildSystemPropertiesStep.kt:65)
	at com.demonwav.mcdev.creator.buildsystem.BuildSystemPropertiesStep$setupUI$1$1.invoke(BuildSystemPropertiesStep.kt:60)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:66)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:53)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:24)
	at com.demonwav.mcdev.creator.buildsystem.BuildSystemPropertiesStep$setupUI$1.invoke(BuildSystemPropertiesStep.kt:60)
	at com.demonwav.mcdev.creator.buildsystem.BuildSystemPropertiesStep$setupUI$1.invoke(BuildSystemPropertiesStep.kt:59)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.indent(PanelImpl.kt:419)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.indent(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$collapsibleGroup$result$1.invoke(PanelImpl.kt:235)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$collapsibleGroup$result$1.invoke(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.impl.CollapsibleRowImpl$3$expandablePanel$1.invoke(CollapsibleRowImpl.kt:65)
	at com.intellij.ui.dsl.builder.impl.CollapsibleRowImpl$3$expandablePanel$1.invoke(CollapsibleRowImpl.kt:18)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:188)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:47)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$panel$1.invoke(PanelImpl.kt:155)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$panel$1.invoke(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:66)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.Panel$DefaultImpls.row$default(Panel.kt:57)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.panel(PanelImpl.kt:154)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.panel(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.impl.CollapsibleRowImpl$3.invoke(CollapsibleRowImpl.kt:64)
	at com.intellij.ui.dsl.builder.impl.CollapsibleRowImpl$3.invoke(CollapsibleRowImpl.kt:18)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:188)
	at com.intellij.ui.dsl.builder.impl.CollapsibleRowImpl.<init>(CollapsibleRowImpl.kt:60)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.collapsibleGroup(PanelImpl.kt:233)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.collapsibleGroup(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.Panel$DefaultImpls.collapsibleGroup$default(Panel.kt:123)
	at com.demonwav.mcdev.creator.buildsystem.BuildSystemPropertiesStep.setupUI(BuildSystemPropertiesStep.kt:59)
	at com.demonwav.mcdev.creator.step.NewProjectWizardChainStep.setupUI(NewProjectWizardChainStep.kt:39)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2$1.invoke(NewProjectWizardStepPanel.kt:21)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2$1.invoke(NewProjectWizardStepPanel.kt:7)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2.invoke(NewProjectWizardStepPanel.kt:20)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel$component$2.invoke(NewProjectWizardStepPanel.kt:7)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.wizard.NewProjectWizardStepPanel.getComponent(NewProjectWizardStepPanel.kt)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$BridgeStep.getComponent(AbstractNewProjectWizardBuilder.kt:69)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$BridgeStep.getComponent(AbstractNewProjectWizardBuilder.kt:60)
	at com.intellij.ide.projectWizard.ProjectTypeStep.showCustomOptions(ProjectTypeStep.java:542)
	at com.intellij.ide.projectWizard.ProjectTypeStep.projectTypeChanged(ProjectTypeStep.java:454)
	at com.intellij.ide.projectWizard.ProjectTypeStep.lambda$new$4(ProjectTypeStep.java:202)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:497)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2205)
	at java.desktop/javax.swing.JList.setSelectedValue(JList.java:2362)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:221)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:64)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:47)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:20)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.performAnActionForComponent(WelcomeScreenActionsUtil.java:96)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil$ToolbarTextButtonWrapper$1.actionPerformed(WelcomeScreenActionsUtil.java:56)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by RedNesto** [comment]
> 2022.1-1.6.2

There's your problem, try with 2023.3.

**Comment by Conutik** [comment]
Just realised idea has been giving me the latest release compatible with my intellij version (which wasn't being auto updated mb)
