### ISSUE TITLE
Issue with latest version

### ISSUE THREAD

**Issue by jaime29010** [DemonWav/MinecraftDevIntelliJ#23]
This exception happened to me twice, with the first one failing while opening the project and another one but with a fully functional project.

```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@10b922 Current thread: Thread[ApplicationImpl pooled thread 199,4,main] 16121638 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1.3#IC-145.1617.8 IDEA, eap:false, os:Windows 10 10.0, java-version:Oracle Corporation 1.8.0_77-b03,6,main] 11433535

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1115)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1099)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1091)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.doAddPane(ProjectViewImpl.java:432)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.doAddUninitializedPanes(ProjectViewImpl.java:387)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.addProjectPane(ProjectViewImpl.java:360)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.ensurePanesLoaded(ProjectViewImpl.java:596)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.getProjectViewPaneById(ProjectViewImpl.java:735)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.getCurrentProjectViewPane(ProjectViewImpl.java:752)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.refresh(ProjectViewImpl.java:757)
	at com.demonwav.mcdev.platform.MinecraftModule.getInstance(MinecraftModule.java:67)
	at com.demonwav.mcdev.platform.MinecraftModule.getInstance(MinecraftModule.java:92)
	at com.demonwav.mcdev.platform.bukkit.BukkitFileIconProvider.getIcon(BukkitFileIconProvider.java:22)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:182)
	at com.intellij.util.IconUtil.access$200(IconUtil.java:49)
	at com.intellij.util.IconUtil$2.fun(IconUtil.java:145)
	at com.intellij.util.IconUtil$2.fun(IconUtil.java:136)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:102)
	at com.intellij.ui.DeferredIconImpl$2.run(DeferredIconImpl.java:152)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

[Thread Dump](https://github.com/DemonWav/MinecraftDevIntelliJ/files/343529/threadDump.txt)

**Comment by DemonWav** [comment]
Whoops! Thanks for the notice!
