### ISSUE TITLE
Add a new Forge project fail

### ISSUE THREAD

**Issue by Little100** [DemonWav/MinecraftDevIntelliJ#2400]
### Minecraft Development for IntelliJ plugin version

1.8.2

### IntelliJ version

2024.3

### Operating System

Windows 11 24H2

### Target platform

Minecraft Forge

### Description of the bug

When I create a Forge project, it keeps prompting me to download versions But no matter what, it cannot be refreshed. The IDE error is as follows

java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog11,0,0,0x0,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=新建项目,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteSafeContext(TransactionGuardImpl.java:159)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.<init>(RefreshSessionImpl.java:62)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.createSession(RefreshQueueImpl.java:194)
	at com.intellij.openapi.vfs.newvfs.RefreshQueue.refresh(RefreshQueue.java:39)
	at com.demonwav.mcdev.util.FilesKt.refreshSync(files.kt:63)
	at com.demonwav.mcdev.creator.custom.providers.RemoteTemplateProvider.doLoadTemplates(RemoteTemplateProvider.kt:143)
	at com.demonwav.mcdev.creator.custom.providers.BuiltinTemplateProvider.loadTemplates(BuiltinTemplateProvider.kt:63)
	at com.demonwav.mcdev.creator.custom.CustomPlatformStep$setupUI$3$1.invokeSuspend(CustomPlatformStep.kt:140)
	at com.demonwav.mcdev.creator.custom.CustomPlatformStep$setupUI$3$1.invoke(CustomPlatformStep.kt)
	at com.demonwav.mcdev.creator.custom.CustomPlatformStep$setupUI$3$1.invoke(CustomPlatformStep.kt)
	at com.demonwav.mcdev.creator.custom.CustomPlatformStep$loadTemplatesInBackground$1.invokeSuspend(CustomPlatformStep.kt:259)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

Everything is normal except for Forge (tried proxy)

**Comment by SparkleArts** [comment]
I have this issue as well in 2023.3.2 in the Version 2023.3-1.8.1!
