### ISSUE TITLE
Unable to create new project for Sponge/Forge plugin

### ISSUE THREAD

**Issue by Evolht** [DemonWav/MinecraftDevIntelliJ#331]
Hey team, unable to create a new project here. Getting the following error:
`java.lang.IllegalArgumentException: Failed to parse version part as integer: 0-SNAPSHOT`

How to reproduce issue:
![image](https://user-images.githubusercontent.com/3460315/34424565-77bb5e50-ec89-11e7-8328-a462610905da.png)
![image](https://user-images.githubusercontent.com/3460315/34424570-7de8238a-ec89-11e7-9228-11f2b703bdfe.png)
![image](https://user-images.githubusercontent.com/3460315/34424581-8c20b11a-ec89-11e7-9d6e-ad42f50c28c1.png)
![image](https://user-images.githubusercontent.com/3460315/34424586-9b62e6de-ec89-11e7-9666-c670ff9f002c.png)
![image](https://user-images.githubusercontent.com/3460315/34424588-a62865bc-ec89-11e7-8f48-5b2817d2c56e.png)

```
java.lang.IllegalArgumentException: Failed to parse version part as integer: 0-SNAPSHOT
java.lang.RuntimeException: java.lang.IllegalArgumentException: Failed to parse version part as integer: 0-SNAPSHOT
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:181)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:661)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem.handleForgeCreate(GradleBuildSystem.kt:488)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem.create(GradleBuildSystem.kt:74)
	at com.demonwav.mcdev.creator.MinecraftProjectCreator$doSingleModuleCreate$1.run(MinecraftProjectCreator.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Failed to parse version part as integer: 0-SNAPSHOT
	at com.demonwav.mcdev.util.SemanticVersion$Companion$parse$1.invoke(SemanticVersion.kt:54)
	at com.demonwav.mcdev.util.SemanticVersion$Companion.parse(SemanticVersion.kt:67)
	at com.demonwav.mcdev.platform.forge.ForgeTemplate.applyBuildGradleTemplate(ForgeTemplate.kt:38)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$handleForgeCreate$$inlined$runWriteTask$2$1.run(Util.kt:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$handleForgeCreate$$inlined$runWriteTask$2.run(Util.kt:145)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:158)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Evolht** [comment]
My best guess is that it can't parse the sponge api version properly.

**Comment by marvin-roesch** [comment]
Whelp, that's what I get for only seeing things from a Forge perspective. I'll submit a PR to honour snapshots ASAP.
