### ISSUE TITLE
Read access is allowed from event dispatch thread or inside read-action only

### ISSUE THREAD

**Issue by MattBDev** [DemonWav/MinecraftDevIntelliJ#36]
```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 19,4,main] 251040830
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.2.1#IU-162.1447.7 IDEA, eap:true, os:Windows 10 10.0, java-version:Oracle Corporation 1.8.0_92-b14,6,main] 1638708094
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:950)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:167)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem.createSubModule(GradleBuildSystem.java:686)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem.createMultiModuleProject(GradleBuildSystem.java:590)
	at com.demonwav.mcdev.creator.MinecraftProjectCreator$2.run(MinecraftProjectCreator.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Please let me know if you need more information.

**Comment by DemonWav** [comment]
Thanks, will be fixed in the next release.
