### ISSUE TITLE
Detector com.demonwav.mcdev.nbt.filetype.NbtFileTypeDetector@4303519b (class com.demonwav.mcdev.nbt.filetype.NbtFileTypeDetector) exception occurred

### ISSUE THREAD

**Issue by ThEWiZ76** [DemonWav/MinecraftDevIntelliJ#362]
`Detector com.demonwav.mcdev.nbt.filetype.NbtFileTypeDetector@4303519b (class com.demonwav.mcdev.nbt.filetype.NbtFileTypeDetector) exception occurred:
java.lang.RuntimeException
	at com.demonwav.mcdev.nbt.Nbt.readByteArrayTag(Nbt.kt:111)
	at com.demonwav.mcdev.nbt.Nbt.readTag(Nbt.kt:145)
	at com.demonwav.mcdev.nbt.Nbt.readCompoundTag(Nbt.kt:74)
	at com.demonwav.mcdev.nbt.Nbt.buildTagTree(Nbt.kt:62)
	at com.demonwav.mcdev.nbt.filetype.NbtFileTypeDetector.detect(NbtFileTypeDetector.kt:26)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:883)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.processTextFromBinaryPresentationOrNull(LoadTextUtil.java:594)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:870)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:820)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:774)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.b(FileTypeManagerImpl.java:819)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.c(FileTypeManagerImpl.java:614)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getFileTypeByFile(FileTypeManagerImpl.java:532)
	at com.intellij.openapi.vfs.VirtualFile.getFileType(VirtualFile.java:346)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:504)
	at com.intellij.util.indexing.FileBasedIndexImpl$UnindexedFilesFinder.processFile(FileBasedIndexImpl.java:2119)
	at com.intellij.util.indexing.FileBasedIndex$1.visitFile(FileBasedIndex.java:163)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:132)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:272)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.util.indexing.FileBasedIndex.iterateRecursively(FileBasedIndex.java:149)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.a(FileBasedIndexScanRunnableCollectorImpl.java:129)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.a(PushedFilePropertiesUpdaterImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.a(PushedFilePropertiesUpdaterImpl.java:295)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Plugin gives me an error.
IntelliJ 2017.3.4
plugin 2017.3-1.1.1
OS Windows 10 x64

**Comment by DenWav** [comment]
This was fixed in d36d754, I just haven't release it yet.
