### ISSUE TITLE
Crash at IDE launch

### ISSUE THREAD

**Issue by Zidane** [DemonWav/MinecraftDevIntelliJ#370]
* Minecraft Development for IntelliJ plugin version: v. 2018.1-1.2.1
* IntelliJ version: 2018.1
* Operating System: Windows 10
* Target platforms: Sponge

```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.Class_utilsKt.getAnonymousIndex(class-utils.kt:147)
	at com.demonwav.mcdev.util.Class_utilsKt.buildQualifiedName(class-utils.kt:262)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:46)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:36)
	at com.demonwav.mcdev.platform.sponge.inspection.SpongeLoggingInspection$Visitor.visitField(SpongeLoggingInspection.kt:53)
	at com.intellij.psi.impl.source.PsiFieldImpl.accept(PsiFieldImpl.java:365)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:278)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:246)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.Class_utilsKt.getAnonymousIndex(class-utils.kt:147)
	at com.demonwav.mcdev.util.Class_utilsKt.buildQualifiedName(class-utils.kt:262)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:46)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:36)
	at com.demonwav.mcdev.platform.sponge.inspection.SpongeLoggingInspection$Visitor.visitField(SpongeLoggingInspection.kt:53)
	at com.intellij.psi.impl.source.PsiFieldImpl.accept(PsiFieldImpl.java:365)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:278)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:246)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.Class_utilsKt.getAnonymousIndex(class-utils.kt:147)
	at com.demonwav.mcdev.util.Class_utilsKt.buildQualifiedName(class-utils.kt:262)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:46)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:36)
	at com.demonwav.mcdev.platform.sponge.inspection.SpongeLoggingInspection$Visitor.visitField(SpongeLoggingInspection.kt:53)
	at com.intellij.psi.impl.source.PsiFieldImpl.accept(PsiFieldImpl.java:365)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:278)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:246)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.Class_utilsKt.getAnonymousIndex(class-utils.kt:147)
	at com.demonwav.mcdev.util.Class_utilsKt.buildQualifiedName(class-utils.kt:262)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:46)
	at com.demonwav.mcdev.util.Class_utilsKt.getFullQualifiedName(class-utils.kt:36)
	at com.demonwav.mcdev.platform.sponge.inspection.SpongeLoggingInspection$Visitor.visitField(SpongeLoggingInspection.kt:53)
	at com.intellij.psi.impl.source.PsiFieldImpl.accept(PsiFieldImpl.java:365)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:278)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:246)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by DenWav** [comment]
I think the best fix to this would be removing the nullable possibility in the `PsiElement.anonymousElement` extension property.

Replace this with `return emptyArray()`.
https://github.com/minecraft-dev/MinecraftDev/blob/e17208b151b0655515552b69ff58c8c887d33cf6/src/main/kotlin/com/demonwav/mcdev/util/class-utils.kt#L166

Which would allow that property to return non-null.

The null-side of this elvis could be simply removed, and I think it would maintain the proper behavior.
https://github.com/minecraft-dev/MinecraftDev/blob/e17208b151b0655515552b69ff58c8c887d33cf6/src/main/kotlin/com/demonwav/mcdev/util/class-utils.kt#L135

And of course, we don't need to yell so much at the compiler here, which is the cause of this issue here.
https://github.com/minecraft-dev/MinecraftDev/blob/e17208b151b0655515552b69ff58c8c887d33cf6/src/main/kotlin/com/demonwav/mcdev/util/class-utils.kt#L147

This would also cause a few more null-handling fixes elsewhere in the code which would be trivially handled. I'm going to sleep now, @Minecrell if you have the time and can look at this and agree that's the correct fix, go ahead and commit the fix and I'll deploy tomorrow.
