### ISSUE TITLE
Kotlin NPE opening Java File

### ISSUE THREAD

**Issue by aikar** [DemonWav/MinecraftDevIntelliJ#388]
Getting this error when opening LootPool.java from an 1.11.2 MCP:

IDEA U 2018.1.4
MC Dev Version: 2018.1-1.2.5

Before I updated Kotlin, this error completely prevented me from opening the file, and didn't even report an error in the UI.
I updated kotlin, and then it correctly associated the error to mc-dev and let me open the file.

```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendInternalName(bytecode-utils.kt:74)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:84)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:137)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.getDescriptor(bytecode-utils.kt:132)
	at com.demonwav.mcdev.util.MemberReferenceKt.getQualifiedMemberReference(MemberReference.kt:128)
	at com.demonwav.mcdev.util.MemberReferenceKt.isSameReference(MemberReference.kt:136)
	at com.demonwav.mcdev.util.Call_utilsKt.getCallsReturningResult(call-utils.kt:77)
	at com.demonwav.mcdev.i18n.translations.TranslationFunction.getCalls(TranslationFunction.kt:54)
	at com.demonwav.mcdev.i18n.translations.TranslationFunction.matches(TranslationFunction.kt:47)
	at com.demonwav.mcdev.i18n.translations.identifiers.TranslationIdentifier$Companion.identify(TranslationIdentifier.kt:47)
	at com.demonwav.mcdev.i18n.translations.identifiers.LiteralTranslationIdentifier.identify(LiteralTranslationIdentifier.kt:21)
	at com.demonwav.mcdev.i18n.translations.identifiers.LiteralTranslationIdentifier.identify(LiteralTranslationIdentifier.kt:17)
	at com.demonwav.mcdev.i18n.translations.identifiers.TranslationIdentifier.identifyUnsafe(TranslationIdentifier.kt:29)
	at com.demonwav.mcdev.i18n.translations.Translation$Companion.fold(Translation.kt:109)
	at com.demonwav.mcdev.i18n.I18nFoldingBuilder.buildFoldRegions(I18nFoldingBuilder.kt:20)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:63)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:236)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:222)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:99)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$updateFoldRegions$0(FoldingUpdate.java:88)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:84)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:310)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:296)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)



```

**Comment by aikar** [comment]
actually looks like its still blocking file opens :/ seems I got the error proper due to disabling kotlin and opening the file, then with the file being open, I triggered the in UI error catcher

**Comment by DenWav** [comment]
This was caused by a non-null requirement on a call to `resolve()`, which can never be guaranteed to be non-null.
