### ISSUE TITLE
StackOverflowError / ResolveCache error

### ISSUE THREAD

**Issue by LatvianModder** [DemonWav/MinecraftDevIntelliJ#435]
I hate the weirdest error ever, apprently from Mc Dev
Basically, one file, Widget.java was acting weird. I couldnt open it in Idea and it showed error. So I copied it method by method, and as soon as I pasted this method in

```java
public boolean handleClick(String click)
{
	int index = click.indexOf(':');

	if (index == -1)
	{
		return handleClick("", click);
	}

	return handleClick(click.substring(0, index), click.substring(index + 1));
}
```

it showed and error and half-crashed. This is the error:

<details>
<summary>Error</summary>

```
null
java.lang.StackOverflowError
	at gnu.trove.TObjectCanonicalHashingStrategy.computeHashCode(TObjectCanonicalHashingStrategy.java:8)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.createHardKey(ConcurrentWeakKeySoftValueHashMap.java:214)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.get(ConcurrentWeakKeySoftValueHashMap.java:222)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.get(ResolveCache.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:198)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:724)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:715)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:424)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:349)
	at com.intellij.psi.impl.source.PsiClassReferenceType.rawType(PsiClassReferenceType.java:199)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1276)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1263)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:237)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1263)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1257)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.erasure(bytecode-utils.kt:68)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendInternalName(bytecode-utils.kt:71)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:78)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:150)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.getDescriptor(bytecode-utils.kt:140)
	at com.demonwav.mcdev.util.MemberReferenceKt.getQualifiedMemberReference(MemberReference.kt:128)
	at com.demonwav.mcdev.util.MemberReferenceKt.isSameReference(MemberReference.kt:136)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:59)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
        <this goes on forever>
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)


java.lang.StackOverflowError
	at gnu.trove.TObjectCanonicalHashingStrategy.computeHashCode(TObjectCanonicalHashingStrategy.java:8)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.createHardKey(ConcurrentWeakKeySoftValueHashMap.java:214)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.get(ConcurrentWeakKeySoftValueHashMap.java:222)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.get(ResolveCache.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:198)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:724)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:715)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:424)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:349)
	at com.intellij.psi.impl.source.PsiClassReferenceType.rawType(PsiClassReferenceType.java:199)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1276)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1263)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:237)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1263)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1257)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.erasure(bytecode-utils.kt:68)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendInternalName(bytecode-utils.kt:71)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:78)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:150)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.getDescriptor(bytecode-utils.kt:140)
	at com.demonwav.mcdev.util.MemberReferenceKt.getQualifiedMemberReference(MemberReference.kt:128)
	at com.demonwav.mcdev.util.MemberReferenceKt.isSameReference(MemberReference.kt:136)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:59)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
        <again, this goes on forever>
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
```
</details>

My method doesn't contain anything special as far as I can tell, so I have no idea what triggers this

**Comment by LatvianModder** [comment]
Looks like it has been reported before by someone unknown, except mine always calls `call-utils.kt:71` not different lines

https://github.com/minecraft-dev/MinecraftDev/issues/402

**Comment by LatvianModder** [comment]
Not even renaming the method/changing its structure a little bit fixes it. I have *no idea*

```java
public final boolean handleClick2(String click)
{
	String[] s = click.split(":", 2);
	return s.length == 2 ? handleClick(s[0], s[1]) : handleClick("", s[0]);
}
```

**Comment by marvin-roesch** [comment]
I'll address this as part of #431. It really is time I get around to indexing translation calls, then we might just be able to implement a "reverse search" ("this calls a known translation function, let's check if it might be one itself") to identify custom translation function.

**Comment by DenWav** [comment]
Sorry, I never remember to work on this stuff when I get home.

**Comment by DenWav** [comment]
This is merged and it'll be deployed soon, sorry for such a long wait.

**Comment by LatvianModder** [comment]
<details>
<summary>Different Error</summary>

```
java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.intellij.util.pico.DefaultPicoContainer.getFromCache(DefaultPicoContainer.java:66)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at com.intellij.psi.impl.source.resolve.ResolveCache.getInstance(ResolveCache.java:49)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:724)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:715)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:434)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:427)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:191)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:138)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1254)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1245)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:237)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1245)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1239)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.erasure(bytecode-utils.kt:69)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendInternalName(bytecode-utils.kt:72)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:79)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:151)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.getDescriptor(bytecode-utils.kt:141)
	at com.demonwav.mcdev.util.MemberReferenceKt.getQualifiedMemberReference(MemberReference.kt:128)
	at com.demonwav.mcdev.util.MemberReferenceKt.isSameReference(MemberReference.kt:136)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:59)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
```
</details>

**Comment by DenWav** [comment]
I _think_ this is fixed...maybe

**Comment by LatvianModder** [comment]
Seems to be working for now
