### ISSUE TITLE
Automatic error reporting doesn't work

### ISSUE THREAD

**Issue by Niko-sk2x** [DemonWav/MinecraftDevIntelliJ#456]
This happens:
![image](https://user-images.githubusercontent.com/1349112/45651178-ea336200-bad0-11e8-96d3-0114ec51d194.png)

* Minecraft Dev version: 2018.2-1.2.10-113
* IntelliJ version: IntelliJ IDEA 2018.2.2 (Community Edition)
  Build #IC-182.4129.33, built on August 21, 2018
  JRE: 1.8.0_171-b11 amd64
  JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
* Operating System: Linux 4.18.5-gentoo

I was unable to find the exact stacktrace in log file.

**Comment by DenWav** [comment]
Yeah, I need to push the fix for that.

**Comment by G-Rath** [comment]
@DemonWav have you been able to push the fix yet? 

I've been unable to report bugs b/c of this :/

**Comment by Niko-sk2x** [comment]
You can just report them here directly for now.

**Comment by DenWav** [comment]
I haven't been able to reproduce, unfortunately. My tests worked fine https://github.com/minecraft-dev/MinecraftDev/issues/455#issuecomment-441117135

**Comment by Niko-sk2x** [comment]
It happens every time for me with the versions I specified, and every version I tried after that, with intellij community and ultimate. If needed I can try some debug version that could provide more detailed information about what happens.

**Comment by Niko-sk2x** [comment]
While trying to get some more useful log and reproducing it again,I also got the following exception when trying to submit a report:
```
java.lang.IllegalStateException: IdeaLogger.ourLastActionId must not be null
	at com.demonwav.mcdev.error.ErrorReporter.submit(ErrorReporter.kt:43)
	at com.intellij.diagnostic.IdeErrorsDialog.reportMessage(IdeErrorsDialog.java:599)
	at com.intellij.diagnostic.IdeErrorsDialog.doOKAction(IdeErrorsDialog.java:374)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1871)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1831)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3315)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
... and then got the string index out of range when tried to report that. But so far I wasn't able to find any more detailed stacktrace.

The exception doesn't appear in idea.log file and it doesn't appear in console even if I modify log.xml to print debug log to console. Intellij just eats the exception and only shows it as this single message.

**Comment by Niko-sk2x** [comment]
Looks like it's actually MinecraftDev eating the exception: https://github.com/minecraft-dev/MinecraftDev/blob/4eab53872af7fb240eac8b711595d4b4344b5eb3/src/main/kotlin/com/demonwav/mcdev/error/ErrorReporter.kt#L89-L98

After creating a modified MinecraftDev that rethrows the exception back, I got this
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -5
    at java.lang.String.substring(String.java:1967)
    at com.demonwav.mcdev.error.AnonymousFeedback.findDuplicateIssue(AnonymousFeedback.kt:121)
    at com.demonwav.mcdev.error.AnonymousFeedback.sendFeedback(AnonymousFeedback.kt:30)
    at com.demonwav.mcdev.error.AnonymousFeedbackTask.run(AnonymousFeedbackTask.kt:31)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by DenWav** [comment]
That's where I'd expect it to be, interesting how the result of the GitHub API is different between calls..

**Comment by Niko-sk2x** [comment]
I don't know why it would work for someone, but it's most likely differences in handling of line endings.
This issue: https://github.com/minecraft-dev/MinecraftDev/issues/432
has been edited, and after editing - it only contains CRLF line endings, instead of `\n` around \`\`\` like in all other autoreported issues. This means that indexOf isn't finding anything, because it's not expecting different line endings. 

The differences can be seen here https://api.github.com/repos/minecraft-dev/MinecraftDev/issues?state=all&creator=minecraft-dev-autoreporter&per_page=100. This is also the only issue that has \`\`\`java instead of \`\`\`, so it can be easily found that way.

This is also one of the last reported issues, with the only issues shown "above" in the results being either reported from MacOS, or some very old intellij version, likely before MinecraftDev had duplicate checks. Before that, there have been a lot more autoreported issues, most of them from windows. So it seems likely that autoreporting now works **only** on macos.

Considering how frequently MinecraftDev throws exceptions for me, once the issue is fixed github is likely to be flooded with autoreported issues (assuming people didn't just give up on trying to use that feature)

**Comment by DenWav** [comment]
Yeah it's so hard following all of IntelliJ's rules for when, how, and where things can and can't be done, considering the rules are documented about as well as blank sheet of paper and seem to change from one version to the next.

I'm sure IntelliJ plugin veterans follow them second nature, but even after 2 years they often seem a mystery.

**Comment by DenWav** [comment]
Also I haven't really been working on this lately, due to lack of time, and I don't know when that will change.

**Comment by DenWav** [comment]
Reproduced on Linux, thanks.
