### ISSUE TITLE
Error when loading a class

### ISSUE THREAD

**Issue by HeyZeer0** [DemonWav/MinecraftDevIntelliJ#468]
Please include the following information in all issues:

* Minecraft Development for IntelliJ plugin version
* IntelliJ version = Intellij Ultimate 2018.2.5
* Operating System = Windows 10

Occurs when loading a class.

`java.lang.StackOverflowError
	at com.intellij.psi.stubs.StubBase.countChildren(StubBase.java:115)
	at com.intellij.psi.stubs.StubBase.getChildrenByType(StubBase.java:104)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStubOrPsiChildren(StubBasedPsiElementBase.java:442)
	at com.intellij.psi.impl.source.tree.java.PsiTypeParameterListImpl.getTypeParameters(PsiTypeParameterListImpl.java:45)
	at com.intellij.psi.impl.PsiImplUtil.getTypeParameters(PsiImplUtil.java:112)
	at com.intellij.psi.impl.source.PsiClassImpl.getTypeParameters(PsiClassImpl.java:340)
	at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:919)
	at com.intellij.psi.impl.source.PsiClassReferenceType.rawType(PsiClassReferenceType.java:202)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1258)
	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1245)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:237)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1245)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1239)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.erasure(bytecode-utils.kt:69)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendInternalName(bytecode-utils.kt:72)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:79)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.appendDescriptor(bytecode-utils.kt:151)
	at com.demonwav.mcdev.util.Bytecode_utilsKt.getDescriptor(bytecode-utils.kt:141)
	at com.demonwav.mcdev.util.MemberReferenceKt.getQualifiedMemberReference(MemberReference.kt:128)
	at com.demonwav.mcdev.util.MemberReferenceKt.isSameReference(MemberReference.kt:136)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:59)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)
	at com.demonwav.mcdev.util.Call_utilsKt.getCalls(call-utils.kt:71)`

**Comment by DenWav** [comment]
This should be fixed, I believe.
