### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by 20zinnm** [DemonWav/MinecraftDevIntelliJ#47]
Not sure what I did to trigger this, but it happened so I thought I'd report it, just in case it's helpful.
```java
2
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$1.lambda$null$1(GradleBuildSystem.java:467)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$1.lambda$run$2(GradleBuildSystem.java:461)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:856)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$1.run(GradleBuildSystem.java:389)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by DemonWav** [comment]
Thanks for the report :)

**Comment by DemonWav** [comment]
Mitigated in 0b313b793a0bcaaad413d6494935c929b714f798
