### ISSUE TITLE
Random java.lang.AssertionError: Already disposed:

### ISSUE THREAD

**Issue by Niko-sk2x** [DemonWav/MinecraftDevIntelliJ#479]
Just happened a few times out of nowhere:

```
java.lang.AssertionError: Already disposed: Module: 'regionlib_main'
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:149)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:35)
	at com.demonwav.mcdev.platform.MinecraftProjectViewNodeDecorator.decorate(MinecraftProjectViewNodeDecorator.kt:44)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0(CompoundProjectViewNodeDecorator.java:49)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach(CompoundProjectViewNodeDecorator.java:60)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate(CompoundProjectViewNodeDecorator.java:49)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:153)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:925)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:126)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:280)
	at com.intellij.ui.tree.StructureTreeModel$Node.access$900(StructureTreeModel.java:256)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$2(StructureTreeModel.java:100)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:117)
	at com.intellij.util.concurrency.Invoker.invokeLaterIfNeeded(Invoker.java:90)
	at com.intellij.ui.tree.StructureTreeModel.invalidate(StructureTreeModel.java:95)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$2(StructureTreeModel.java:113)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:117)
	at com.intellij.util.concurrency.Invoker.invokeLaterIfNeeded(Invoker.java:90)
	at com.intellij.ui.tree.StructureTreeModel.invalidate(StructureTreeModel.java:95)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$2(StructureTreeModel.java:113)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:117)
	at com.intellij.util.concurrency.Invoker.invokeLaterIfNeeded(Invoker.java:90)
	at com.intellij.ui.tree.StructureTreeModel.invalidate(StructureTreeModel.java:95)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$2(StructureTreeModel.java:113)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:121)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:77)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:260)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DenWav** [comment]
Fixed in 18fd2e6bccf55332546e38b725a1bf12befa5cef
