### ISSUE TITLE
Exception thrown , too long to summarize in title.

### ISSUE THREAD

**Issue by ryantheleach** [DemonWav/MinecraftDevIntelliJ#51]
I created a new Sponge module, accidentally inside my SpongeForge module which has been correctly identifed as a forge module.

I closed intellij then moved the module to my top level Sponge folder which contains SpongeForge + plugins.

I restarted intellij, and it reported the following exception.

IntelliJ IDEA 2016.2.3 EAP
Build #IU-162.1812.2, built on August 16, 2016
--snip--
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

MinecraftDevIntelliJ alpha-0.1.9 from the IntelliJ repository.

```
0
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$1.lambda$run$2(GradleBuildSystem.java:393)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:856)
	at com.demonwav.mcdev.buildsystem.gradle.GradleBuildSystem$1.run(GradleBuildSystem.java:389)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by DemonWav** [comment]
Fixed in 0b313b793a0bcaaad413d6494935c929b714f798
