### ISSUE TITLE
Error during IJ startup

### ISSUE THREAD

**Issue by kennytv** [DemonWav/MinecraftDevIntelliJ#655]
The very first thing appearing when opening IJ is the error (followed by the autodisable)

* Minecraft Development for IntelliJ plugin version: 2019.2-1.3.0
* IntelliJ version: 2019.2.2
* Operating System: Win 10
* Running Java 8
```
com.intellij.diagnostic.PluginException: While loading class com.demonwav.mcdev.i18n.I18nFileListener: com/demonwav/mcdev/i18n/I18nFileListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: com.demonwav.minecraft-dev]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:221)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:165)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:73)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:386)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.registerComponents(ApplicationImpl.java:382)
    at com.intellij.idea.IdeaApplication.lambda$registerRegistryAndMessageBusAndComponent$7(IdeaApplication.java:182)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at com.intellij.idea.IdeaApplication.initApplication(IdeaApplication.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.proceed(MainImpl.java:98)
    at com.intellij.ide.a.h.ar.proceed(ar.java:128)
    at com.intellij.ide.a.h.ah.c(ah.java:528)
    at com.intellij.ide.a.h.ah.e(ah.java:484)
    at com.intellij.ide.a.h.ah.a(ah.java:432)
    at com.intellij.ide.a.h.ah.d(ah.java:174)
    at com.intellij.ide.a.h.ah.b(ah.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1.start(MainImpl.java:89)
    at com.intellij.idea.StartupUtil.lambda$prepareAndStart$7(StartupUtil.java:237)
    at com.intellij.util.ui.EdtInvocationManager.executeWithCustomManager(EdtInvocationManager.java:49)
    at com.intellij.idea.StartupUtil.prepareAndStart(StartupUtil.java:232)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl.start(MainImpl.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:58)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedClassVersionError: com/demonwav/mcdev/i18n/I18nFileListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:218)
    ... 44 more
```

**Comment by RedNesto** [comment]
Please update the plugin to `2019.2-1.3.1`.

**Comment by kennytv** [comment]
Hmm had to reinstall the plugin for it to find the update, weird. but thanks, works now
