### ISSUE TITLE
UI freeze caught by IntelliJ

### ISSUE THREAD

**Issue by Janrupf** [DemonWav/MinecraftDevIntelliJ#684]
## Details:
* Plugin version: 2020.01-1.3.2
* IntelliJ version: 2020.01 EAP (201.6251.22)
* Operating System: Arch Linux, kernel 5.5.8-arch1-1
* Target platforms: None (loading normal gradle project, no minecraft involved at all)

## What happened?
The IDE has frozen multiple times when using this plugin. It looks like Jetbrains added a new feature in the 2020 IDE's which detects deadlocks, but I already had this issue on older IDE's (I just was never able to figure out which plugin was causing it). 

## Stacktrace:
```
Freeze for 60 seconds
IDE KILLED! Sampled time: 53400ms, sampling rate: 100ms, GC time: 55ms (0%), Class loading: 0%, load average: 2.64

The stack is from the thread that was blocking EDT

com.intellij.diagnostic.Freeze
	at com.demonwav.mcdev.platform.mixin.inspection.MixinInspection.buildVisitor(MixinInspection.kt:27)
	at com.intellij.codeInspection.LocalInspectionTool.buildVisitor(LocalInspectionTool.java:124)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:53)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:306)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$3(LocalInspectionsPass.java:273)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3640/0x0000000802d65840.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:154)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:146)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$4(LocalInspectionsPass.java:270)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3626/0x0000000802d55840.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:270)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3612/0x0000000802d52c40.process(Unknown Source)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3241/0x000000080264a440.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3242/0x0000000802649840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.concurrency.ApplierCompleter$$Lambda$3240/0x000000080264a040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base@11.0.6/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base@11.0.6/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1708)
	at java.base@11.0.6/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:276)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:196)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3065/0x00000008024f9c40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3053/0x00000008024fc440.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3044/0x00000008024fe040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base@11.0.6/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base@11.0.6/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

## Suspected cause
Unknown. Maybe MaterialThemeUI?

## Other things
IntelliJ also threw this at me, in case it helps you:
```
 java.util.concurrent.ForkJoinWorkerThread.run 53200ms
  java.util.concurrent.ForkJoinPool.runWorker 53200ms
   java.util.concurrent.ForkJoinPool.scan 53200ms
    java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec 53200ms
     java.util.concurrent.ForkJoinTask.doExec 53200ms
      com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec 53200ms
       com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run 53200ms
        com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader 53200ms
         com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader 53200ms
          com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3044/0x00000008024fe040.run 53200ms
           com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0 53200ms
            com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun 53200ms
             com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress 53200ms
              com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress 53200ms
               com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun 53200ms
                com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3053/0x00000008024fc440.run 53200ms
                 com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2 53200ms
                  com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction 53200ms
                   com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$3065/0x00000008024f9c40.run 53200ms
                    com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1 53200ms
                     com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation 53200ms
                      com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation 53200ms
                       com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress 53200ms
                        com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect 53200ms
                         com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit 53200ms
                          com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress 53200ms
                           com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress 53200ms
                            java.util.concurrent.ForkJoinTask.get 53200ms
                             java.util.concurrent.ForkJoinPool.awaitJoin 53200ms
                              java.util.concurrent.ForkJoinTask.doExec 53200ms
                               java.util.concurrent.CountedCompleter.exec 53200ms
                                com.intellij.concurrency.ApplierCompleter.compute 53200ms
                                 com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader 53200ms
                                  com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader 53200ms
                                   com.intellij.concurrency.ApplierCompleter$$Lambda$3240/0x000000080264a040.run 53200ms
                                    com.intellij.concurrency.ApplierCompleter.lambda$compute$0 53200ms
                                     com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator 53200ms
                                      com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress 53200ms
                                       com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress 53200ms
                                        com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun 53200ms
                                         com.intellij.concurrency.ApplierCompleter$$Lambda$3242/0x0000000802649840.run 53200ms
                                          com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1 53200ms
                                           com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction 53200ms
                                            com.intellij.concurrency.ApplierCompleter$$Lambda$3241/0x000000080264a440.run 53200ms
                                             com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks 53200ms
                                              com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks 53200ms
                                               com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks 53200ms
                                                com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3612/0x0000000802d52c40.process 53200ms
                                                 com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5 53200ms
                                                  com.intellij.util.AstLoadingFilter.disallowTreeLoading 53200ms
                                                   com.intellij.util.AstLoadingFilter.disallowTreeLoading 53200ms
                                                    com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3626/0x0000000802d55840.compute 53200ms
                                                     com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$4 53200ms
                                                      com.intellij.util.AstLoadingFilter.forceAllowTreeLoading 53200ms
                                                       com.intellij.util.AstLoadingFilter.forceAllowTreeLoading 53200ms
                                                        com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$$Lambda$3640/0x0000000802d65840.compute 53200ms
                                                         com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$3 53200ms
                                                          com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements 53200ms
                                                           com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements 53200ms
                                                            com.intellij.codeInspection.LocalInspectionTool.buildVisitor 53200ms
                                                             com.demonwav.mcdev.platform.mixin.inspection.MixinInspection.buildVisitor 53200ms
 java.awt.EventDispatchThread.run 200ms
  java.awt.EventDispatchThread.pumpEvents 200ms
   java.awt.EventDispatchThread.pumpEvents 200ms
    java.awt.EventDispatchThread.pumpEventsForHierarchy 200ms
     java.awt.EventDispatchThread.pumpEventsForFilter 200ms
      java.awt.EventDispatchThread.pumpOneEventForFilters 200ms
       com.intellij.ide.IdeEventQueue.dispatchEvent 200ms
        com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread 200ms
         com.intellij.ide.IdeEventQueue$$Lambda$504/0x00000008006a9840.run 200ms
          com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9 200ms
           com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized 200ms
            com.intellij.ide.IdeEventQueue$$Lambda$507/0x00000008006d1840.compute 200ms
             com.intellij.ide.IdeEventQueue.lambda$null$8 200ms
              com.intellij.ide.IdeEventQueue._dispatchEvent 200ms
               com.intellij.ide.IdeEventQueue.defaultDispatchEvent 200ms
                java.awt.EventQueue.dispatchEvent 200ms
                 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege 200ms
                  java.security.AccessController.doPrivileged 200ms
                   java.awt.EventQueue$4.run 200ms
                    java.awt.EventQueue$4.run 200ms
                     java.awt.EventQueue.dispatchEventImpl 200ms
                      java.awt.event.InvocationEvent.dispatch 200ms
                       com.intellij.openapi.application.impl.FlushQueue$FlushNow.run 200ms
                        com.intellij.openapi.application.impl.FlushQueue.flushNow 200ms
                         com.intellij.openapi.application.impl.FlushQueue.runNextEvent 200ms
                          com.intellij.openapi.application.impl.FlushQueue.doRun 200ms
                           com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$284/0x00000008004d0040.run 200ms
                            com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4 200ms
                             com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread 200ms
                              com.intellij.openapi.application.TransactionGuardImpl$2.run 200ms
                               com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission$$Lambda$870/0x0000000800bee840.run 200ms
                                com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6 200ms
                                 com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$860/0x0000000800ba3440.accept 200ms
                                  com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$869/0x0000000800bef040.run 200ms
                                   com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.lambda$runAsyncListeners$6 200ms
                                    com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents 200ms
                                     com.intellij.openapi.application.WriteAction.run 200ms
                                      com.intellij.openapi.application.WriteAction.start 200ms
                                       com.intellij.openapi.application.impl.ApplicationImpl.acquireWriteActionLock 200ms
                                        com.intellij.openapi.application.impl.ApplicationImpl$WriteAccessToken.<init> 200ms
                                         com.intellij.openapi.application.impl.ApplicationImpl.access$300 200ms
                                          com.intellij.openapi.application.impl.ApplicationImpl.startWrite 200ms
                                           com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock 200ms
                                            java.util.concurrent.locks.LockSupport.parkNanos 100ms
                                             jdk.internal.misc.Unsafe.park 100ms
                                            com.intellij.openapi.application.impl.ReadMostlyRWLock.areAllReadersIdle 100ms
```

**Comment by RedNesto** [comment]
Do you have many similar freeze reports blaming the plugin in a similar way?

That's because I'm not sure why the EDT is blocked, I've never encountered those freezes despite using my potato-ish computer.
My guess is that inspections (from all plugins) take too much time, and one of our inspection was executed when IntelliJ decided to record the stacktrace & sampler results, kinda the same way Minecraft's watchdog works. That would mean we are not blocking the inspection worker (and the EDT somehow).

I may be completely wrong though, we need to see other reports to make sure it is caused by the plugin and to be able to spot performance issues.

**Comment by Janrupf** [comment]
Well, I think a 60 second lock on a Threadripper should never occur because of CPU intensive code. This more looks like a resource deadlock. Moreover, there were only 3 external plugins enabled:
- MaterialThemeUI
- Atom Material Icons
- Minecraft Dev

The project was empty despite the gradle build structure, there weren't even classes in it.
In general, the crash happened 2 times:
1. Using the "Apply gradle wrapper with sources" action
2. Opening the project from the toolbox
