### ISSUE TITLE
NBT fileType redeclaration

### ISSUE THREAD

**Issue by TerraSpecOp** [DemonWav/MinecraftDevIntelliJ#706]
* Minecraft Development for IntelliJ plugin version 2020.1-1.3.2
* IntelliJ version 2020.1
* Operating System MacOS Sierra
* Target platform 

```
com.intellij.diagnostic.PluginException: Trying to override already registered file type NBT [Plugin: com.demonwav.minecraft-dev]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.loadFileTypeBeans(FileTypeManagerImpl.java:421)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:309)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:221)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:645)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$future$1.run(ComponentManagerImpl.kt:787)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by K4zoku** [comment]
same error

**Comment by TONY-All** [comment]
Also this error..

**Comment by RedNesto** [comment]
Not sure what to do about this, looks like a conflict with another plugin.

It would really help if somebody find what plugin is also registering the NBT file type.

Edit: could be https://plugins.jetbrains.com/plugin/12839-minecraft-nbt-support

**Comment by KisaragiEffective** [comment]
@RedNesto 
agree, I found out that I’ve installed it when looking plugin list.

**Comment by K4zoku** [comment]
> Edit: could be https://plugins.jetbrains.com/plugin/12839-minecraft-nbt-support

That's it, I turned it off and no more errors

**Comment by RedNesto** [comment]
Welp, I have no idea how to resolve this conflit. I don't think we can register extension points only if a plugin _isn't_ installed.
Maybe extracting MCDev's NBT support into a separate plugin ? Not sure how much it is tied to the plugin right now.

**Comment by RedNesto** [comment]
For reference, it was also reported on their repo: tth05/minecraft-nbt-intellij-plugin#5

**Comment by DenWav** [comment]
BashSupport does this check ever since Jetbrains added shell support themselves. Will need to look into how that's accomplished.

**Comment by DenWav** [comment]
I think the easiest fix is for them to change their file type name away from `NBT`, since that's what we were already using. I'll look into a way of us not registering our NBT `fileType` if that other plugin is already installed. Since mcdev is a much larger plugin if both are installed the user probably wants to use their NBT editor.

**Comment by DenWav** [comment]
More info here https://github.com/tth05/minecraft-nbt-intellij-plugin/issues/5#issuecomment-645105460

**Comment by RedNesto** [comment]
I believe this was fixed on the NBT plugin side. If you encounter this error make sure to update the NBT plugin.
