### ISSUE TITLE
Unable to update plugin without IntelliJ restart

### ISSUE THREAD

**Issue by StepByStepler** [DemonWav/MinecraftDevIntelliJ#770]
* Minecraft Development for IntelliJ plugin version: 2020.2-1.5.0-181
* IntelliJ version: 2020.2.1 RC #IU-202.6948.36
* Operating System: Windows 10 20H2 19042.450
* Target platform, if relevant: Bukkit (might be applicable to all platforms)

```
java.lang.ExceptionInInitializerError
	at com.demonwav.mcdev.facet.MinecraftLibraryKindsKt.<clinit>(MinecraftLibraryKinds.kt:27)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener$autoDetectTypes$1.invoke(MinecraftFacetDetector.kt:108)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener$autoDetectTypes$1.process(MinecraftFacetDetector.kt:34)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.lambda$forEachLibrary$1(OrderEnumeratorBase.java:361)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.processEntries(OrderEnumeratorBase.java:324)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEach(ModuleOrderEnumerator.java:33)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.forEachLibrary(OrderEnumeratorBase.java:357)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEachLibrary(ModuleOrderEnumerator.java:17)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.autoDetectTypes(MinecraftFacetDetector.kt:107)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.checkExistingFacet(MinecraftFacetDetector.kt:82)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.doCheck(MinecraftFacetDetector.kt:53)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector.runActivity(MinecraftFacetDetector.kt:31)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:300)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$000(StartupManagerImpl.java:54)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$extensionAdded$2(StartupManagerImpl.java:276)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:348)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:340)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Kind bukkit-api is not unique
	at com.intellij.openapi.roots.libraries.LibraryKind.<init>(LibraryKind.java:36)
	at com.intellij.openapi.roots.libraries.LibraryKind.create(LibraryKind.java:55)
	at com.demonwav.mcdev.platform.bukkit.framework.BukkitLibraryKindKt.<clinit>(BukkitLibraryKind.kt:15)
	... 45 more
```

IntelliJ automatically reloads plugin after updating it, so user doesn't have to restart whole IDE. It seems like MinecraftDev plugin doesn't work after reloading and shows this stacktrace.

Reproduce steps:
1. Receive IntelliJ notification `"Minecraft Development" plugin update available`
2. Click `update` button
3. Wait until IntelliJ updates plugin
4. Receive IntelliJ exception

**Comment by RedNesto** [comment]
This was fixed some time ago.
