### ISSUE TITLE
Problem with indexing in new versions of forge

### ISSUE THREAD

**Issue by kim-kostya** [DemonWav/MinecraftDevIntelliJ#794]
Problem with code indexing in classes where used @Mod.EventBusSubscriber.

In the project setup there were some problems with compiling forge mdk(Method duplications, method `getName` in enums).

```
Plugin version: 2020.2-1.5.1
IDE version: 	2020.2.3
OS:	        Windows 10 x64
FML:		Forge 1.16.3-34.1.33
MCP:		stable 60-1.15
```

Stacktrace:
```
java.lang.IllegalArgumentException: Multiple entries with same key: MemberReference(name=getName, descriptor=()Ljava/lang/String;, owner=net.minecraft.world.biome.Biome$Category, matchAll=false)=MemberReference(name=func_222352_a, descriptor=()Ljava/lang/String;, owner=net.minecraft.world.biome.Biome$Category, matchAll=false) and MemberReference(name=getName, descriptor=()Ljava/lang/String;, owner=net.minecraft.world.biome.Biome$Category, matchAll=false)=MemberReference(name=func_176610_l, descriptor=()Ljava/lang/String;, owner=net.minecraft.world.biome.Biome$Category, matchAll=false)
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableBiMap.fromEntryArray(RegularImmutableBiMap.java:86)
	at com.google.common.collect.ImmutableBiMap$Builder.build(ImmutableBiMap.java:291)
	at com.demonwav.mcdev.platform.mcp.srg.TinySrgParser.parseSrg(TinySrgParser.kt:68)
	at com.demonwav.mcdev.platform.mcp.srg.SrgManager$parse$$inlined$runAsync$1.run(promise.kt:401)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RedNesto** [comment]
I'm pretty sure this is happening because you are using 1.15 mappings for 1.16.4, try 
`mappings channel: 'snapshot', version: '20201028-1.16.3'` instead.

**Comment by kim-kostya** [comment]
It didn't help

**Comment by kim-kostya** [comment]
Thanks for help
