### ISSUE TITLE
Exception during initialization

### ISSUE THREAD

**Issue by ChloeDawn** [DemonWav/MinecraftDevIntelliJ#807]
**2020.2-1.5.1/2020.2-1.5.2**
When I attempted to update to 1.5.2 whilst a project was open, it rolled back to 1.5.2 and produced this exception. The exception was seemingly avoided if I ensured all projects were closed before updating, though. Possibly something related to caching? Unsure. Felt I should report it regardless.

```
IntelliJ IDEA 2020.2.4 (Community Edition)
Build #IC-202.8194.7, built on November 24, 2020
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1975M
Cores: 8
Non-Bundled Plugins: GLSL, Lombook Plugin, String Manipulation, com.jetbrains.plugins.ini4idea, com.almightyalpaca.intellij.plugins.discord, com.jetbrains.codeWithMe, org.toml.lang, org.jetbrains.kotlin, zielu.gittoolbox, PythonCore, com.demonwav.minecraft-dev
```
```
java.lang.ExceptionInInitializerError
	at com.demonwav.mcdev.facet.MinecraftLibraryKindsKt.<clinit>(MinecraftLibraryKinds.kt:27)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener$autoDetectTypes$1.invoke(MinecraftFacetDetector.kt:108)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener$autoDetectTypes$1.process(MinecraftFacetDetector.kt:34)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.lambda$forEachLibrary$1(OrderEnumeratorBase.java:361)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.processEntries(OrderEnumeratorBase.java:324)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEach(ModuleOrderEnumerator.java:33)
	at com.intellij.openapi.roots.impl.OrderEnumeratorBase.forEachLibrary(OrderEnumeratorBase.java:357)
	at com.intellij.openapi.roots.impl.ModuleOrderEnumerator.forEachLibrary(ModuleOrderEnumerator.java:17)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.autoDetectTypes(MinecraftFacetDetector.kt:107)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.checkExistingFacet(MinecraftFacetDetector.kt:82)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector$MinecraftModuleRootListener.doCheck(MinecraftFacetDetector.kt:53)
	at com.demonwav.mcdev.facet.MinecraftFacetDetector.runActivity(MinecraftFacetDetector.kt:31)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:300)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$000(StartupManagerImpl.java:54)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$extensionAdded$2(StartupManagerImpl.java:276)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:348)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:340)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Kind bukkit-api is not unique
	at com.intellij.openapi.roots.libraries.LibraryKind.<init>(LibraryKind.java:36)
	at com.intellij.openapi.roots.libraries.LibraryKind.create(LibraryKind.java:55)
	at com.demonwav.mcdev.platform.bukkit.framework.BukkitLibraryKindKt.<clinit>(BukkitLibraryKind.kt:15)
	... 45 more
```

**Comment by RedNesto** [comment]
That's expected, the plugin can't be properly reloaded yet (most remaining errors happen only when doing certain actions before reloading.)
This specific error (`Kind blah is not unique`) should be fixed in 1.5.2 though, so it should not be a problem for the next releases.
