### ISSUE TITLE
NoSuchMethodError if mods.toml file is open

### ISSUE THREAD

**Issue by Hubry** [DemonWav/MinecraftDevIntelliJ#830]
Reproduction: Open `mods.toml` and look in bottom right - the error icon should appear without any input other than opening the file/moving the caret. Autocompletion seems to still work for entry values.

* Plugin version: 2020.3-1.5.3
* TOML plugin version: 0.2.141.3674-203
* Target platform: Forge + Mixin
* Project used: [Botania](https://github.com/Vazkii/Botania)

IDE about page dump:
> IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1975M
Cores: 8
Non-Bundled Plugins: com.github.b3er.idea.plugins.arc.browser, org.toml.lang, PMD-IDEA, com.demonwav.minecraft-dev, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets

```
java.lang.NoSuchMethodError: 'java.util.List org.toml.lang.psi.TomlTableHeader.getNames()'
	at com.demonwav.mcdev.toml.TomlSchemaKt.getSchema(TomlSchema.kt:65)
	at com.demonwav.mcdev.toml.TomlSchemaKt.access$getSchema$p(TomlSchema.kt:1)
	at com.demonwav.mcdev.toml.TomlSchema$Companion.parse(TomlSchema.kt:54)
	at com.demonwav.mcdev.toml.platform.forge.ModsTomlSchema.get(ModsTomlSchema.kt:23)
	at com.demonwav.mcdev.toml.platform.forge.inspections.ModsTomlValidationInspection$Visitor.visitValue(ModsTomlValidationInspection.kt:100)
	at com.demonwav.mcdev.toml.TomlElementVisitor.visitElement(TomlElementVisitor.kt:24)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.accept(CompositePsiElement.java:215)
	at org.toml.lang.psi.impl.TomlLiteralImpl.accept(Psi.kt:97)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:66)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:298)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:267)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:266)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:266)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by RedNesto** [comment]
This is already fixed in the nightly channel.

**Comment by Hubry** [comment]
Looks like I should've checked more branches than just the default one 🤔
